spring:
  application:
    name: finance-tracker
  main:
    banner-mode: off
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  # driver config
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # open means connection status is open, and view is controller

server:
  servlet:
    context-path: /api/v1.0

app:
  mail-config:
    from-email: ${BREVO_FROM_EMAIL}
    support-name: "Finance Tracker Support"